### ISSUE TITLE
ImportError: DLL load failed while importing numpy_ops

### ISSUE THREAD

**Issue by JejTr** [nathfavour/bionicpython#2]
OS: Windows 10 

To replicate:
1. Download Zip package repository
2. Install Requirements.txt ---> pip install -r Requirements.txt
3. Run bionicpython.py <path.pdf>*

_Traceback (most recent call last):
  File "\Downloads\bionicpython-master\bionicpython-master\bionicpython\bionicpython.py", line 9, in <module>
    import spacy
  File "\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\compat.py", line 39, in <module>
    from thinc.api import Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\api.py", line 1, in <module>
    from .backends import (
  File "AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\backends\__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\backends\cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
ImportError: DLL load failed while importing numpy_ops: No se puede encontrar el módulo especificado._

**Comment by nathfavour** [comment]
Hi, sorry for your error...I think it's related to a numpy_ops library.

I only tested bionicpython on Mac
Pending the time I work on it, can you reinstall numpy

**Comment by mohamadalzhori** [comment]
I just tested it on my windows 11 machine, it works fine. 
Also previously used it on ubuntu, so I can confirm that it works fine.

**Comment by nathfavour** [comment]
Nice. I will soon publish to pip package to make it easier to use
